### ISSUE TITLE
Large file in the repository

### ISSUE THREAD

**Issue by olexandr-konovalov** [Stefan-Kohl/stefan-kohl.github.io#1]
When pushing the initial commit to GitHub, the following warning appeared:
```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File tmp/Ischia_2014.zip is 54.19 MB; this is larger than GitHub's recommended maximum file size of 50.00 M
```
Do you still need that file (the directory name suggests that the answer might be no).

**Comment by Stefan-Kohl** [comment]
That file is no more needed -- I have removed it (like some other bigger files which are not needed any more in this place).

**Comment by olexandr-konovalov** [comment]
Ok, so I will close this issue. BTW, I've recently used a lot https://github.com/fingolfin/ReleaseTools and https://github.com/fingolfin/GitHubPagesForGAP, and that works amazingly well. It's a push-button solution to make releases, and archives are not stored in the webpage repository - they are retrieved from GitHub because certain revisions are marked as releases (see e.g. https://github.com/gap-packages/example/releases). You need to follow instructions and spend some time on setting up (~30 minutes for the 1st package that you try to automate?) and then each next release may be published within several minutes.
