### ISSUE TITLE
Splitting off package pages

### ISSUE THREAD

**Issue by olexandr-konovalov** [Stefan-Kohl/stefan-kohl.github.io#2]
This personal website contains subdirectories for three GAP packages: FactInt, RCWA and ResClasses. That was sensible when this was the content of `public_html` directory, but for the future perhaps you may consider modularising this repository by splitting packages into separate repositories. Ideally they would contain both packages' source code and their website, and could be migrated to https://github.com/gap-packages.

**Comment by Stefan-Kohl** [comment]
I'm not sure about this, as this also depends on future decisions on hosting and tools used for development.

**Comment by olexandr-konovalov** [comment]
Let's think about this later - I deliberately said "perhaps" "for the future". Independently on hosting, having (source code of) packages in separate repositories one virtual organisation has its own remit, especially those which GAP loads by default.

**Comment by Stefan-Kohl** [comment]
I think this is mainly a question which becomes relevant when other people would like to collaborate on my packages (they are GPL'ed in the end). For my purposes as a single developer, GIT is actually far too fancy -- experience so far shows that I use a VCS mainly for bookkeeping ("when have I added what?", etc.), and rarely for much else.

**Comment by olexandr-konovalov** [comment]
It's a chicken-egg question. Does one need to share a source code to attract collaborators, or to wait until being explicitly asked by someone? If the code is already available, prospective collaborators have at least one less step - they don't have to write to you, and then maybe lost interest. Instead they can fork your repository and submit a pull request why they are on it. For example, if there are any changes in GAP requiring changes in packages, we can just submit pull request to packages in https://github.com/gap-packages (still to let their authors to decide).

**Comment by Stefan-Kohl** [comment]
Well -- this might rather summon the kind of contributions I am not sure I like. -- If someone would like to make nontrivial contributions, expressing their intentions is certainly not asked too much.

**Comment by olexandr-konovalov** [comment]
Anyhow, I suggest that we should keep this discussion dormant for a while. If you will have time, you may have a look at [this reading](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004947) in the meantime.

**Comment by Stefan-Kohl** [comment]
I have deleted my last comment, since it seems that you completely misunderstood it
(cf. my answer to your mail).

**Comment by olexandr-konovalov** [comment]
BTW, there are only five Mercurial repositories belonging to package authors outside St Andrews which are still hosted on the Mercurial service at MCS, and three of them are yours. We can not guarantee that we will indefinitely support them, so I'd like again to suggest to move them to GitHub, or, if you prefer to keep using Mercurial, to Bitbucket. We can plan this in advance and help to that to happen, to avoid situation when this will be as urgent as recent migration of your homepage.

**Comment by olexandr-konovalov** [comment]
P.S. Using bitbucket will only change the place where the repository is hosted, it will not affect your workflow otherwise. And you and users of your packages will also be able to use issue tracker there. Although, as you see at http://gap-packages.github.io/ the majority is on GitHub.

**Comment by Stefan-Kohl** [comment]
This issue cannot be compared to breaking the homepage. -- The purpose of having copies of the package repositories on the Mercurial service at MCS is merely having a convenient means of maintaining remote backups. -- Will the copies of the repositories in my mcs account continue to work? -- If yes, the impact of switching off the Mercurial service at MCS on me is almost negligible (my present setup is 3-step: local copy of the repository on my laptop --> copy of the repository in my mcs account --> copy of the repository on the Mercurial service at MCS). If not, things get less convenient, but there is still no reason to immediately do anything.

**Comment by olexandr-konovalov** [comment]
Yeah, with a distributed VCS like Git or Mercurial you of course may keep a full clone of the repository (with all branches if you use any) and you will be able to push it to e.g. Bitbucket at any time. But while you believe that the impact of switching off the Mercurial service at MCS on you will be negligible, it would not be negligible for the GAP project when a repository moves from a place where it can be accessible by other developers to be hidden in your private account. I would expect that package authors picking up repositories made from old CVS `pkg` directory will embrace open development model and follow the mainstream. Especially for a package like FactInt which is loaded by default when GAP starts, is used to speed up integer factorisation, and had no changes in the codebase since 2011 (do you have plans to keep to be its maintainer?)

**Comment by Stefan-Kohl** [comment]
As indicated, changes in the setup, and in particular a switch to a multi-developer environment, need to be discussed once other people volunteer to contribute -- and this is unrelated from this-or-that service being switched off or not. What concerns FactInt: so far my last significant change to the package was an update of the factor database for integers of the form a^k+/-1 in response to a request from Alexander (H.), who reported that certain numbers which he tried to factor couldn't be factored with FactInt although factorizations were already known; this was in June 2011 and led to the release of FactInt 1.5.3. Since that, as far as I remember, nobody reported any bugs or shortcomings in FactInt -- so, assuming that people still use the package, it seems that everything is working fine. -- Since you are asking: do you wish to further improve the code or implement new algorithms?

**Comment by olexandr-konovalov** [comment]
What I'd really want to do is to add tests and code coverage results using Travis CI and CodeCov, and then start to improve code coverage by adding more tests.

**Comment by Stefan-Kohl** [comment]
This sounds rather like administrative tasks than like collaboration as a developer. -- You are certainly welcome to set up things in a suitable way for this, and if that setup appears to make life easier for me, I will be happy to make use of it as well. -- By the way, I have released today FactInt 1.5.4 (with only cosmetic changes). Will the new PackageInfo.g URL's be found automatically?

**Comment by olexandr-konovalov** [comment]
I expect new `PackageInfo.g` to be found - today that happened to RCWA and ResClasses already. For tests and code coverage results, I need a repository on GitHub to start with, preferably under https://github.com/gap-packages. If you're happy, we can convert existing FactInt Mercurial repository and place it there.

**Comment by Stefan-Kohl** [comment]
Yes -- thank you!

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl wrote:
> This sounds rather like administrative tasks than like collaboration as a developer. -- You are certainly welcome to set up things in a suitable way for this, and if that setup appears to make life easier for me, I will be happy to make use of it as well. 

First, I think it's a task of a developer to ensure that the code is tested. Second, to set up things in a suitable way I would first need a public repository, one per package. 

I run coverage for FactInt, and in general it's well tested:

![screen shot 2017-03-06 at 22 20 44](https://cloud.githubusercontent.com/assets/5751387/23633481/d6e0e23a-02bd-11e7-8fd8-b23759047249.png)

However, the file `general.gi` does not cover the following:
- the case when `Result := FactorsTDNC(-n);` is called in `FactorsTDNC`
- all code after line `if f(k) <> n then return [[],[n]]; fi;` in `FactorsMultFunc`
- `else` part in `FactorsPowerCheck`
- `FactorsFermat` only tests the case when it returns within the `repeat ... until` loop
- some lines in `FactorsAurifeuillian` 
- `FactInt` with `cheap` option 
- Special cases for Primorial(k) +/- , Fibonacci numbers, 11111111... and some 'naive' methods in `FactInt`
- some cases in `IntegerFactorization` 
- `PartialFactorization` (missed completely)

You can see the attached zip-file for the full details.
[factint_gap_general.gi.html.zip](https://github.com/Stefan-Kohl/stefan-kohl.github.io/files/822729/factint_gap_general.gi.html.zip)

If you would like to reproduce this, I've run

```
gapdev -r -A --cover output.gz test.g 
```
where `test.g` has lines
```
LoadPackage("factint");
Test("factint.tst");
QUIT;
```
and then in another GAP session
```
LoadPackage("profiling");
OutputAnnotatedCodeCoverageFiles( "output.gz", "output-directory-name");
```

This may not work on Windows, so you may run this on Linux machine and then download output files to analyse, what's a bit awkward - setting up a package repository with Travis CI to run the test and CodeCov to see the coverage will make life easier, indeed.

**Comment by Stefan-Kohl** [comment]
@alex-konovalov You are taking back your kind offer you made 3 weeks ago and which I welcomed?

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl ah, so your `Yes -- thank you!` 3 weeks ago was the answer to "For tests and code coverage results, I need a repository on GitHub to start with, preferably under https://github.com/gap-packages. If you're happy, we can convert existing FactInt Mercurial repository and place it there." ? I probably not seen it, then we'll certainly be happy to do this!

**Comment by Stefan-Kohl** [comment]
@alex-konovalov Thank you! -- By the way, this will be not the first public git repository for FactInt -- there is e.g. already a Debian one [here](https://anonscm.debian.org/cgit/debian-science/packages/gap-factint.git/tree/).

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl ok. That Debian repository is apparently a part of Debian release workflow, and it does not have actual commits history from the development version of FactInt, so that's not some we are interested in reusing.

**Comment by Stefan-Kohl** [comment]
@alex-konovalov Of course!

**Comment by Stefan-Kohl** [comment]
@alex-konovalov I have now amended FactInt's standard tests, in order to improve code coverage.
In particular, coverage for lib/general.gi is now better.

**Comment by olexandr-konovalov** [comment]
Thanks, very good! I am keeping in mind setting up automated CI tests for it - will talk on this later.

By the way, to keep this information closer to the package, next time I would suggest to create an issue at https://github.com/gap-packages/FactInt/issues. This may later be helpful to track which issue has been addressed in which version. If you will ping me there, I will be notified too.

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl After observing how this works for FactInt, perhaps it's time to spin off RCWA and ResClasses? Would you be interested in getting any help with this?

**Comment by Stefan-Kohl** [comment]
@alex-konovalov Well -- the difference between the packages is the following: FactInt is widely used (at least I assume so!), and I am quite confident that it is in good hands basically regardless of who in the GAP Group takes maintainership. -- But as far as it concerns RCWA and ResClasses, I haven't seen anyone else in the GAP Group so far who really cares to keep these packages working. Once this changes, I'd be more than happy to at least share maintainership of these packages with someone else as well.

**Comment by olexandr-konovalov** [comment]
>But as far as it concerns RCWA and ResClasses, I haven't seen anyone else in the GAP Group so far who really cares to keep these packages working. 

I don't agree with this. I think other people reporting problems to you, and suggesting to make a proper repository demonstrates the opposite. We are also monitoring situations when changes in the core system break packages, including yours. Otherwise, there would be a simple option to move the package to https://www.gap-system.org/Packages/Contrib/contrib.html and stop including it in the main distribution archive. 

> Once this changes, I'd be more than happy to at least share maintainership of these packages with someone else as well.

It's also a "chicken and egg" problem. Making a proper repository will make the code more accessible to potential contributors. You are saying "I will wait for them first". They are saying "There is no even a public repository, that's so inconvenient". I think the onus here is on the owner of the code to make the first step.

**Comment by olexandr-konovalov** [comment]
Now we have:
* https://github.com/gap-packages/FactInt
* https://github.com/gap-packages/resclasses 
* https://github.com/gap-packages/rcwa

so perhaps you may close this issue when appropriate (maybe after RCWA and ResClasses will have a release made from GitHub and you will adjust their pages in this repository).

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl your website still has pages for these three packages, and they do not list their latest releases. What are you going to do with them? Set up redirect to the new pages?

**Comment by Stefan-Kohl** [comment]
@alex-konovalov The old pages link to the new ones for the recent releases. Since they do contain information which is not present on the new pages, simply deleting them would not be a good solution.

**Comment by olexandr-konovalov** [comment]
Fine with me as long as this is a design choice and not an oversight - just checking. I will close this issue then. Although, it may be nice to increase the font or do something else to make that text about newer releases being published elsewhere more visible.
