### ISSUE TITLE
ResClasses use obsolete USER_HOME_EXPAND, replace by UserHomeExpand

### ISSUE THREAD

**Issue by olexandr-konovalov** [Stefan-Kohl/stefan-kohl.github.io#7]
It is used in `lib/general.gi` in ResClasses. Should be `UserHomeExpand`, see

https://github.com/gap-system/gap/blob/262e53d0513b507ad187278f28557245e8345cd4/lib/obsolete.gd#L582

**Comment by Stefan-Kohl** [comment]
Firstly -- where in RCWA do you see USER_HOME_EXPAND being used? -- I find this only in ResClasses (lib/general.gi).  Secondly -- UserHomeExpand does not seem to exist at all in GAP 4.8.8:

    gap> UserHomeExpand;
    Error, Variable: 'UserHomeExpand' must have a value

Thirdly -- is there a particular reason to remove  USER_HOME_EXPAND in the future -- is it perhaps in the way of something?

**Comment by olexandr-konovalov** [comment]
1) You're right - only in ResClasses. It appears in the log for RCWA, but only because of dependencies.

2) It will appear in GAP 4.9. Indeed, you may wait, if you intend to publish another version for GAP 4.8.

3. It will be cleaner to use `UserHomeExpand` to get rid of warnings in tests with `-O` option. As https://github.com/gap-system/gap/blob/262e53d0513b507ad187278f28557245e8345cd4/lib/obsolete.gd#L582 says, it got a nicer name and became documented in https://github.com/gap-system/gap/blob/10b8b8cc794c7c3577a05f3cfe50f234b7dcb048/lib/string.g#L328.

**Comment by Stefan-Kohl** [comment]
In my opinion, incompatible changes always need some good reason, and finding a particular name nicer than an existing one hardly qualifies as such. -- Don't you think so? -- I mean, of course nicer names can always be introduced in addition, as synonyms.

**Comment by olexandr-konovalov** [comment]
In GAP, with perhaps some rare exceptions, all capitals style is used for internal functions, and documented functionality usually use "CamelCase". IMHO it's a good reason to introduce a new name.

You're not in a hurry to change to using a new name (I forgot that it's not yet in GAP 4.8, looking at test logs for GAP 4.9 RC), but it will be useful to switch to new name in the future. For example, a user studying your code may try `?USER_HOME_EXPAND` and get nothing, or `? UserHomeExpand` and see the docs.

**Comment by olexandr-konovalov** [comment]
Done in https://github.com/gap-packages/resclasses/commit/35b6bcead240b255d61dd2c62d26b805785c67db
